### ISSUE TITLE
Thumbnails generated but all black

### ISSUE THREAD

**Issue by tyeeman** [stuporglue/InstaGallery#13]
Just trying this out. Looks good, but all my thumbnails are 1711 bytes and black, no image. gd2 is enabled in my php. Anything come to mind?

**Comment by stuporglue** [comment]
I would enable the PHP error log and set an appropriate log level, I expect that gd2 is probably logging errors and should point you in the right direction.

**Comment by tyeeman** [comment]
ok, I'll try that. Also when using localhost I'm getting a failure to find local folders. This is a sample url that fails - 
```
http://localhost/instagallery/?d=G:\path\to\images\Photos
```

**Comment by stuporglue** [comment]
I would suspect the windows url might be causing problems. I've never used
a Windows php server and haven't tested paths like that.

**Comment by tyeeman** [comment]
I tried removing the path like this - 

```
http://localhost/instagallery/?d=Photos
```
and it works fine. What would I change in the code to do this?

I'm also noticing that my images are cropped a little. Is that supposed to happen?
