### ISSUE TITLE
Some PNG files are black, most are displaying correct.

### ISSUE THREAD

**Issue by LeonardoBerkhout** [stuporglue/InstaGallery#14]
I listed a directory with 80 PNG files. 7 files are listed as black thumbnails.
I've checked the files online, but they are nice. When you click in the  InstaGallery, the picture behind the black thumbnail will be viewed correctly.
Closing the file will show the thumbnail index again, but with the same thumbnails black.

I have tried to save the PNG files with different programs and upload them again, but that doesn't solve the problem. When I convert a PNG file to a JPG file, also the new JPG thumbnail is black.
The filenames has no special characters and no space are used, they are _ signs.

I have uploaded a video file too, it can play in the thumbnail.
But there is no thumbnail of the MP4 file, a preview should be nice.
The server directory has write access....

Goodlooking Gallery anyway, love it! Keep the good work!

**Comment by kgorecki** [comment]
@LeonardoBerkhout can you share example of PNG file which has black thumbnail?
