### ISSUE TITLE
Delete Image/Video

### ISSUE THREAD

**Issue by twostarii** [stuporglue/InstaGallery#20]
Firstly thank you for the library, how can we add a Delete icon next to the Download button?

**Comment by stuporglue** [comment]
Hi twostarii, 

While this project does have htaccess based authentication, it is not a fully secure login method. I do not feel comfortable adding a way to delete content from a user's server with the existing authentication. 

If your use case is different somehow, you should be able to have a developer add a custom plugin similar to how the instaGallery_download.inc plugin works.
